name: Lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  pre-commit:
    name: pre-commit-hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install eslint deps
        run: |
          curl -O https://raw.githubusercontent.com/cesium-ml/baselayer_template_app/refs/heads/main/package.json
          npm install --only=dev
          npm audit --audit-level critical
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
